load metaInterpreter.maude
load predef_modules.maude
load aux_modules.maude
load grammar.maude
load file.maude
load allSS.maude  --- fichero a cargar de prueba: softset vending-machine

fmod COMMAND-PROCESSING is
 pr QUANTIFICATION-OPS .
 pr PARSING-RESULT .
 pr META-LEVEL .
 pr LEXICAL .

 vars RIG RIG' NOM NOM' FLE FLE' SS : SortSet .
 vars M M' M'' TOP TOP' FLAT FLAT' : Module .
 vars VS VS' UV UV' EV EV' : VariableSet .
 vars T T' T'' T1 T2 T3 T4 TQ : Term .
 vars QIL QIL' ERR ERR' : QidList .
 vars PL PL' : ParameterDeclList .
 vars TL TL' ACC : TermList .
 var  SSDS : SubsortDeclSet .
 var  RP? : [ResultPair] .
 var  COND : Condition .
 var  PR : ParsingRes .
 var  ODS : OpDeclSet .
 var  TyL : TypeList .
 vars Ty Ty' : Type .
 var  AtS : AttrSet .
 var  DB : Database .
 vars S S' : String .
 var  Eq : Equation .
 vars Q Q' FQ : Qid .
 var  V : Variable .
 var  OP : OpDecl .
 var  I : Import .
 var  Srt : Sort .
 var  H : Header .
 var  N : Nat .


 op parseModule : Term -> ParsingRes .
 ceq parseModule('spec!_=_end[T,T']) = parseNoBubbles(M, T')
  if H := parseHeader(T) /\
     M := emptyModule(H) .
 ceq parseModule('spec*_=_end[T,T']) = parseNoBubbles(M, T')
  if H := parseHeader(T) /\
     M := emptyTheory(H) .

 op parseNoBubbles : Module Term -> ParsingRes .
 ceq parseNoBubbles(M, '__[T, T']) = [M'', (TL, TL'),
                                      < (RIG ; RIG'), (NOM ; NOM'), (FLE ; FLE') >, ERR ERR' ]
  if [M', TL, < RIG, NOM, FLE >, ERR] := parseDefNoBubble(M, T) /\
     [M'', TL', < RIG', NOM', FLE' >, ERR'] := parseNoBubbles(M', T') .
 eq parseNoBubbles(M, T) = parseDefNoBubble(M, T) .

 op parseDefNoBubble : Module Term -> ParsingRes .
 ***(
           PARSING IMPORTATION DECLARATIONS
 )
 ceq parseDefNoBubble(M, 'pr_.['token[T]]) = [M', empty, < none, none, none >, nil ]
  if Q := downQid(T) /\
     I := protecting Q . /\
     M' := addImports(M, I) .
 ceq parseDefNoBubble(M, 'ex_.['token[T]]) = [M', empty, < none, none, none >, nil ]
  if Q := downQid(T) /\
     I := extending Q . /\
     M' := addImports(M, I) .
 ceq parseDefNoBubble(M, 'inc_.['token[T]]) = [M', empty, < none, none, none >, nil ]
  if Q := downQid(T) /\
     I := including Q . /\
     M' := addImports(M, I) .
 ***(
           PARSING SORT DECLARATIONS
 )
 ceq parseDefNoBubble(M, 'rigid`sort_.['neTokenList[T]]) = [M', empty, < SS, none, none >, nil ]
  if SS := parseSortList(T) /\
     M' := addSorts(M, SS) .
 ceq parseDefNoBubble(M, 'rigid`sorts_.['neTokenList[T]]) = [M', empty, < SS, none, none >, nil ]
  if SS := parseSortList(T) /\
     M' := addSorts(M, SS) .
 ceq parseDefNoBubble(M, 'nominal`sort_.['neTokenList[T]]) = [M'', empty, < none, SS, none >, nil ]
  if SS := parseSortList(T) /\
     M' := addSorts(M, SS) /\
     SSDS := genSubsortNominal(SS) /\
     M'' := addSubsorts(M', SSDS) .
 ceq parseDefNoBubble(M, 'nominal`sorts_.['neTokenList[T]]) = [M'', empty, < none, SS, none >, nil ]
  if SS := parseSortList(T) /\
     M' := addSorts(M, SS) /\
     SSDS := genSubsortNominal(SS) /\
     M'' := addSubsorts(M', SSDS) .
 ceq parseDefNoBubble(M, 'sort_.['neTokenList[T]]) = [M', empty, < none, none, SS >, nil ]
  if SS := parseSortList(T) /\
     M' := addSorts(M, SS) .
 ceq parseDefNoBubble(M, 'sorts_.['neTokenList[T]]) = [M', empty, < none, none, SS >, nil ]
  if SS := parseSortList(T) /\
     M' := addSorts(M, SS) .
 ***(
          SUBSORTS, OPERATORS, EQUATIONS, AND VARIABLES ARE PARSED LATED.
          It makes sense because they might need sorts, kinds, and operators from imported modules
          and parameters.
 )
 eq parseDefNoBubble(M, T) = [M, T, < none, none, none >, nil ] [owise] . *** TODO!!!

 op parseArity : Term -> TypeList .
 eq parseArity('__[TL]) = parseArity*(TL) .
 eq parseArity(T) = downQid(T) [owise] .

 op parseArity* : TermList -> TypeList .
 eq parseArity*((T, TL)) = downQid(T) parseArity*(TL) .
 eq parseArity*(empty) = nil .

 op parseSortList : Term -> SortSet .
 eq parseSortList('__[TL]) = parseSortList*(TL) .
 eq parseSortList(T) = downQid(T) [owise] .

 op parseSortList* : TermList -> SortSet .
 eq parseSortList*((T, TL)) = downQid(T) ; parseSortList*(TL) .
 eq parseSortList*(empty) = none .

 op genSubsortNominal : SortSet -> SubsortDeclSet .
 eq genSubsortNominal(none) = none .
 eq genSubsortNominal(Srt ; SS) = subsort Srt < '@Nominal@ . genSubsortNominal(SS) .

 op parseAttr : Module Term -> AttrSet .
 eq parseAttr(M, '__[TL]) = parseAttr*(M, TL) .
 eq parseAttr(M, 'ctor.@Attr@) = ctor .
 eq parseAttr(M, 'iter.@Attr@) = iter .
 eq parseAttr(M, 'assoc.@Attr@) = assoc .
 eq parseAttr(M, 'comm.@Attr@) = comm .
 eq parseAttr(M, 'idem.@Attr@) = idem .
 eq parseAttr(M, 'memo.@Attr@) = memo .
 eq parseAttr(M, 'id:_['bubble[T]]) = memo . *** TODO

 op parseAttr* : Module TermList -> AttrSet .
 eq parseAttr*(M, empty) = none .
 eq parseAttr*(M, (T, TL)) = parseAttr(M, T) parseAttr*(M, TL) .

 ***(
 ops id:_ : @Bubble@ -> @Attr@ .
 op prec_ : @Token@ -> @Attr@ .
 op metadata_ : @Token@ -> @Attr@ .
 )

***(
      Header
)
 op parseHeader : Term -> Header .
 ceq parseHeader('token[T]) = Q
  if Q := downQid(T) .
 ceq parseHeader('_`{_`}['token[T], T']) = Q{PL}
  if Q := downQid(T) /\
     PL := parsePL(T') .

 op parsePL : Term -> ParameterDeclList .
 ceq parsePL('_`,_[T, T']) = PL, PL'
  if PL := parsePL(T) /\
     PL' := parsePL(T') .
 ceq parsePL('_::_['token[T], 'token[T']]) = Q :: Q'
  if Q := downQid(T) /\
     Q' := downQid(T') .

 *** Top module, Flat module, Vars and equations
 op parseBubbles : Module Module TermList -> ParsingRes .
 eq parseBubbles(TOP, FLAT, TL) = parseBubbles(TOP, FLAT, none, TL, empty) .

 ***(
             PARSE VARIABLES
 )
 *** Top module, Flat module, VariableSet, Vars and equations, Acc
 op parseBubbles : Module Module VariableSet TermList TermList -> ParsingRes .
 eq parseBubbles(TOP, FLAT, VS, empty, ACC) = parseEqs(TOP, FLAT, VS, ACC) .
 ceq parseBubbles(TOP, FLAT, VS, ('var_:_.['neTokenList[T],'token[T']], TL), ACC) =
                             parseBubbles(TOP, FLAT, VS ; VS', TL, ACC)
  if VS' := parseVars(T, T') .
 ceq parseBubbles(TOP, FLAT, VS, ('vars_:_.['neTokenList[T],'token[T']], TL), ACC) =
                             parseBubbles(TOP, FLAT, VS ; VS', TL, ACC)
  if VS' := parseVars(T, T') .
 ***(
           PARSING SUBSORT DECLARATIONS
 )
 ceq parseBubbles(TOP, FLAT, VS, ('subsort_<_.['neTokenList[T],'token[T']], TL), ACC) = parseBubbles(TOP', FLAT', VS, TL, ACC)
  if SS := parseSortList(T) /\
     Ty := downQid(T') /\
     SSDS := createSubsortDecls(SS, Ty) /\
     TOP' := addSubsorts(TOP, SSDS) /\
     FLAT' := addSubsorts(FLAT, SSDS) .
 ***(
           PARSING OP DECLARATIONS
 )
 ceq parseBubbles(TOP, FLAT, VS, ('op_:`->_.['token[T],'token[T']], TL), ACC) = parseBubbles(TOP', FLAT', VS, TL, ACC)
  if Q := downQid(T) /\
     Q' := downQid(T') /\
     OP := op Q : nil -> Q' [none] . /\
     TOP' := addOps(TOP, OP) /\
     FLAT' := addOps(FLAT, OP) .
 ceq parseBubbles(TOP, FLAT, VS, ('op_:`->_`[_`].['token[T],'token[T'], T''], TL), ACC) =
                                                                                parseBubbles(TOP', FLAT', VS, TL, ACC)
  if Q := downQid(T) /\
     Q' := downQid(T') /\
     AtS := parseAttr(FLAT, T'') /\
     OP := op Q : nil -> Q' [AtS] . /\
     TOP' := addOps(TOP, OP) /\
     FLAT' := addOps(FLAT, OP) .
 ceq parseBubbles(TOP, FLAT, VS, ('op_:_->_.['token[T],'neTokenList[T'],'token[T'']], TL), ACC) =
                                                                                parseBubbles(TOP', FLAT', VS, TL, ACC)
  if Q := downQid(T) /\
     TyL := parseArity(T') /\
     Q' := downQid(T'') /\
     OP := op Q : TyL -> Q' [none] . /\
     TOP' := addOps(TOP, OP) /\
     FLAT' := addOps(FLAT, OP) .
 ceq parseBubbles(TOP, FLAT, VS, ('op_:_->_`[_`].['token[T1],'neTokenList[T2],'token[T3], T4], TL), ACC) =
                                                                                parseBubbles(TOP', FLAT', VS, TL, ACC)
  if Q := downQid(T1) /\
     TyL := parseArity(T2) /\
     Q' := downQid(T3) /\
     AtS := parseAttr(FLAT, T4) /\
     OP := op Q : TyL -> Q' [AtS] . /\
     TOP' := addOps(TOP, OP) /\
     FLAT' := addOps(FLAT, OP) .
 ***(
           PARSING PARTIAL OP DECLARATIONS
 )
 ceq parseBubbles(TOP, FLAT, VS, ('op_:`~>_.['token[T],'token[T']], TL), ACC) = parseBubbles(TOP', FLAT', VS, TL, ACC)
  if Q := downQid(T) /\
     Q' := downQid(T') /\
     OP := op Q : nil -> Q' [none] . /\
     TOP' := addOps(TOP, OP) /\
     FLAT' := addOps(FLAT, OP) .
 ceq parseBubbles(TOP, FLAT, VS, ('op_:`~>_`[_`].['token[T],'token[T'], T''], TL), ACC) =
                                                                      parseBubbles(TOP', FLAT', VS, TL, ACC)
  if Q := downQid(T) /\
     Q' := downQid(T') /\
     AtS := parseAttr(FLAT, T'') /\
     OP := op Q : nil -> Q' [AtS] . /\
     TOP' := addOps(TOP, OP) /\
     FLAT' := addOps(FLAT, OP) .
 ceq parseBubbles(TOP, FLAT, VS, ('op_:_~>_.['token[T],'neTokenList[T'],'token[T'']], TL), ACC) =
                                                                      parseBubbles(TOP', FLAT', VS, TL, ACC)
  if Q := downQid(T) /\
     TyL := parseArity(T') /\
     Q' := downQid(T'') /\
     OP := op Q : toKind(FLAT, TyL) -> toKind(FLAT, Q') [none] . /\
     TOP' := addOps(TOP, OP) /\
     FLAT' := addOps(FLAT, OP) .
 ceq parseBubbles(TOP, FLAT, VS, ('op_:_~>_`[_`].['token[T1],'neTokenList[T2],'token[T3], T4], TL), ACC) =
                                                                      parseBubbles(TOP', FLAT', VS, TL, ACC)
  if Q := downQid(T1) /\
     TyL := parseArity(T2) /\
     Q' := downQid(T3) /\
     AtS := parseAttr(FLAT, T4) /\
     OP := op Q : toKind(FLAT, TyL) -> toKind(FLAT, Q') [AtS] . /\
     TOP' := addOps(TOP, OP) /\
     FLAT' := addOps(FLAT, OP) .
 ***(
           PARSING FLEXIBLE OP DECLARATIONS
 )
 ceq parseBubbles(TOP, FLAT, VS, ('flexible`op_:`->_.['token[T],'token[T']], TL), ACC) = parseBubbles(TOP', FLAT', VS, TL, ACC)
  if Q := downQid(T) /\
     FQ := createFlexOpName(Q, nil) /\
     Q' := downQid(T') /\
     ODS := (op FQ : '@Nominal@ -> Q' [none] .
             op Q : nil -> Q' [none] .) /\
     TOP' := addOps(TOP, ODS) /\
     FLAT' := addOps(FLAT, ODS) .
 ceq parseBubbles(TOP, FLAT, VS, ('flexible`op_:`->_`[_`].['token[T],'token[T'], T''], TL), ACC) =
                                                                               parseBubbles(TOP', FLAT', VS, TL, ACC)
  if Q := downQid(T) /\
     FQ := createFlexOpName(Q, nil) /\
     Q' := downQid(T') /\
     AtS := parseAttr(FLAT, T'') /\
     ODS := (op FQ : '@Nominal@ -> Q' [AtS] .
             op Q : nil -> Q' [AtS] .) /\
     TOP' := addOps(TOP, ODS) /\
     FLAT' := addOps(FLAT, ODS) .
 ceq parseBubbles(TOP, FLAT, VS, ('flexible`op_:_->_.['token[T],'neTokenList[T'],'token[T'']], TL), ACC) =
                                                                               parseBubbles(TOP', FLAT', VS, TL, ACC)
  if TyL := parseArity(T') /\
     Q := downQid(T) /\
     FQ := createFlexOpName(Q, TyL) /\
     Q' := downQid(T'') /\
     ODS := (op FQ : '@Nominal@ TyL -> Q' [none] .
             op Q : TyL -> Q' [none] .) /\
     TOP' := addOps(TOP, ODS) /\
     FLAT' := addOps(FLAT, ODS) .
 ceq parseBubbles(TOP, FLAT, VS, ('flexible`op_:_->_`[_`].['token[T1],'neTokenList[T2],'token[T3], T4], TL), ACC) =
                                                                               parseBubbles(TOP', FLAT', VS, TL, ACC)
  if TyL := parseArity(T2) /\
     Q := downQid(T1) /\
     FQ := createFlexOpName(Q, TyL) /\
     Q' := downQid(T3) /\
     AtS := parseAttr(FLAT, T4) /\
     ODS := (op FQ : '@Nominal@ TyL -> Q' [AtS] .
             op Q : TyL -> Q' [AtS] .) /\
     TOP' := addOps(TOP, ODS) /\
     FLAT' := addOps(FLAT, ODS) .

 ***(
           PARSING PREDICATES
 )
 eq parseBubbles(TOP, FLAT, VS, ('pred_.[T], TL), ACC) =
              parseBubbles(TOP, FLAT, VS, ('op_:`->_.[T,'token[''Bool.Qid]], TL), ACC) .

 eq parseBubbles(TOP, FLAT, VS, ('pred_`[_`].['token[T],T''], TL), ACC) =
              parseBubbles(TOP, FLAT, VS, ('op_:`->_`[_`].['token[T],'token[''Bool.Qid], T''], TL), ACC) .
 eq parseBubbles(TOP, FLAT, VS, ('pred_:_.['token[T],'neTokenList[T']], TL), ACC) =
              parseBubbles(TOP, FLAT, VS, ('op_:_->_.['token[T],'neTokenList[T'],'token[''Bool.Qid]], TL), ACC) .
 eq parseBubbles(TOP, FLAT, VS, ('pred_:_`[_`].['token[T1],'neTokenList[T2],T4], TL), ACC) =
              parseBubbles(TOP, FLAT, VS, ('op_:_->_`[_`].['token[T1],'neTokenList[T2],'token[''Bool.Qid], T4], TL), ACC) .
 ***(
             OWISE
 )
 eq parseBubbles(TOP, FLAT, VS, (T, TL), ACC) = parseBubbles(TOP, FLAT, VS, TL, (ACC, T)) [owise] .

 ***(
             PARSE EQUATIONS
 )
 op parseEqs : Module Module VariableSet TermList -> ParsingRes .
 eq parseEqs(TOP, FLAT, VS, empty) = [TOP, VS, nil] .
 ceq parseEqs(TOP, FLAT, VS, (T, TL)) = parseEqs(M, FLAT, VS, TL)
  if Eq := parseEq(FLAT, VS, T) /\
     M := addEqs(TOP, Eq) .

 op parseEq : Module VariableSet Term -> Equation .
 ceq parseEq(M, VS, 'eq_=_.['bubble[T], 'bubble[T']]) = eq T1 = T2 [none] .
  if QIL := downQidList(T) /\
     QIL' := downQidList(T') /\
     {T1, Ty} := metaParse(M, VS, QIL, anyType) /\
     {T2, Ty'} := metaParse(M, VS, QIL', anyType) .
 op parseEq : Module VariableSet Term -> Equation .
 ceq parseEq(M, VS, 'eq_._=_.[TQ, 'bubble[T], 'bubble[T']]) = eq T1 = T2 [AtS] .
  if QIL := downQidList(T) /\
     QIL' := downQidList(T') /\
     {T1, Ty} := metaParse(M, VS, QIL, anyType) /\
     {T2, Ty'} := metaParse(M, VS, QIL', anyType) /\
     < UV, EV > := extractQuantVars(TQ, VS) /\
     AtS := generateQuantificationAtts(UV, EV) .
 ceq parseEq(M, VS, 'ceq_=_if_.['bubble[T], 'bubble[T'],T'']) = ceq T1 = T2 if COND [none] .
  if QIL := downQidList(T) /\
     QIL' := downQidList(T') /\
     {T1, Ty} := metaParse(M, VS, QIL, anyType) /\
     {T2, Ty'} := metaParse(M, VS, QIL', anyType) /\
     COND := parseCondition(M, T'', VS) .
 ceq parseEq(M, VS, 'ceq_._=_if_.[TQ, 'bubble[T], 'bubble[T'],T'']) = ceq T1 = T2 if COND [AtS] .
  if QIL := downQidList(T) /\
     QIL' := downQidList(T') /\
     {T1, Ty} := metaParse(M, VS, QIL, anyType) /\
     {T2, Ty'} := metaParse(M, VS, QIL', anyType) /\
     COND := parseCondition(M, T'', VS) /\
     < UV, EV > := extractQuantVars(TQ, VS) /\
     AtS := generateQuantificationAtts(UV, EV) .

 op parseCondition : Module Term VariableSet -> Condition .
 eq parseCondition(M, '_/\_[TL], VS) = parseCondition*(M, TL, VS) .
 ceq parseCondition(M, '_=_['bubble[T], 'bubble[T']], VS) = (T1 = T2)
  if QIL := downQidList(T) /\
     QIL' := downQidList(T') /\
     {T1, Ty} := metaParse(M, VS, QIL, anyType) /\
     {T2, Ty'} := metaParse(M, VS, QIL', anyType) .

 op parseCondition* : Module TermList VariableSet -> Condition .
 eq parseCondition*(M, empty, VS) = nil .
 eq parseCondition*(M, (T, TL), VS) = parseCondition(M, T, VS) /\ parseCondition*(M, TL, VS) .

 op parseVars : Term Term -> VariableSet .
 ceq parseVars(T, T') = createVars(QIL, Ty)
  if QIL := parseVars(T) /\
     Ty := downQid(T') .

 op parseVars : Term -> QidList .
 eq parseVars('__[TL]) = parseVars*(TL) .
 eq parseVars(T) = downQid(T) [owise] .

 op parseVars* : TermList -> QidList .
 eq parseVars*(empty) = nil .
 eq parseVars*((T, TL)) = downQid(T) parseVars*(TL) .

 op createVars : QidList Type -> VariableSet .
 eq createVars(nil, Ty) = none .
 ceq createVars(Q QIL, Ty) = V ; createVars(QIL, Ty)
  if V := qid(string(Q) + ":" + string(Ty)) .

 op extractTerms : Term -> TermList .
 eq extractTerms('__[TL]) = extractTerms*(TL) .
 eq extractTerms(T) = T [owise] .

 op extractTerms* : TermList -> TermList .
 eq extractTerms*(empty) = empty .
 eq extractTerms*((T, TL)) = extractTerms(T), extractTerms*(TL) .

 op createSubsortDecls : SortSet Type -> SubsortDeclSet .
 eq createSubsortDecls(none, Ty) = none .
 eq createSubsortDecls(Ty ; SS, Ty') = subsort Ty < Ty' .
                                       createSubsortDecls(SS, Ty') .

 op createFlexOpName : Qid TypeList -> Qid .
 eq createFlexOpName(Q, nil) = qid("@_" + string(Q)) .
 eq createFlexOpName(Q, TyL) = $createFlexOpName(Q, | TyL |) [owise] .

 op $createFlexOpName : Qid NzNat -> Qid .
 ceq $createFlexOpName(Q, N) = qid("@_" + string(Q))
  if S := string(Q) /\
     find(S, "_", 0) =/= notFound .
 ceq $createFlexOpName(Q, N) = Q'
  if S := string(Q) /\
     find(S, "_", 0) == notFound /\
     Q' := qid("@_" + string(Q) + addUnderscores(N)) .

 op |_| : TypeList -> Nat .
 eq | nil | = 0 .
 eq | Ty TyL | = s(| TyL |) .

 op addUnderscores : NzNat -> String .
 eq addUnderscores(N) = "(" + $addUnderscores(N) + ")" .

 op $addUnderscores : NzNat -> String .
 eq $addUnderscores(1) = "_" .
 eq $addUnderscores(s(N)) = "_," + $addUnderscores(N) [owise] .

 op vars2str : VariableSet -> String .
 eq vars2str(none) = "" .
 eq vars2str(V) = string(V) .
 eq vars2str(V ; VS) = string(V) + " ; " + vars2str(VS) [owise] .

 op generateQuantificationAtts : VariableSet VariableSet -> AttrSet .
 eq generateQuantificationAtts(UV, none) = none .
 eq generateQuantificationAtts(UV, EV) = nonexec metadata(vars2str(EV)) .
endfm

mod PLSS is
 pr (MAYBE * (op maybe to noMod)){Module} .
 pr (MAYBE * (op maybe to noQid)){Qid} .
 pr (MAYBE * (op maybe to null)){Oid} .
 pr COMMAND-PROCESSING .
 inc META-INTERPRETER .
 pr META-PLSS-SIGN .
 pr PRELOAD-LIST .
 inc STD-STREAM .
 pr ERROR-MSGS .
 pr DATABASE .
 inc FILE .

 vars Text Original Read Source STR MSG : String .
 vars TL TL' BUBBS MODL IN INPLST : TermList .
 vars T T' T'' T1 T2 T3 T4 : Term .
 vars FHIn FHOut MI : Oid .
 var  MM : Maybe{Module} .
 var  AtS : AttributeSet .
 var  LP : List{Preload} .
 vars DB DB' : Database .
 vars QIL ERR : QidList .
 vars M M' TOP : Module .
 var  VS : VariableSet .
 var  MQ : Maybe{Qid} .
 var  SI : SortInfo .
 vars Ty Ty' : Type .
 var  Q : Qid .
 var  N : Nat .

 sort State .
 *** Initial state, metainterpreter is created
 op init : -> State [ctor] .
 *** Loading from standard database
 op load-std-db : -> State [ctor] .
 *** Loading grammar
 op load-grammar : -> State [ctor] .
 *** Load user modules
 op load-user-mod : -> State [ctor] .
 *** Waiting input from the user
 op idle : -> State [ctor] .
 *** Reading file
 op readFile : -> State [ctor] .
 *** Parsing Module - metaparse
 op parseModMetaparse : -> State [ctor] .
 *** Parsing - create module list
 op parseList : -> State [ctor] .
 *** Parsing Module
 op parseModBubbles : -> State [ctor] .
 *** Parsing Module
 op parseModule : -> State [ctor] .
 *** Get parsed module
 op getModule : -> State [ctor] .
 *** Parsing command
 op parseComm : -> State [ctor] .
 *** Execute command
 op executeComm : -> State [ctor] .
 *** Waits for a wrote msg and returns to idle with getLine
 op print&idle : -> State [ctor] .
 *** Waits for a wrote msg and keeps executing commands.
 op print&executeComm : -> State [ctor] .


 *** Object and class definition
 op PLSS : -> Cid .
 op plss : -> Oid .

 *** Attributes
 op load:_ : List{Preload} -> Attribute [ctor gather (&)] .
 op parsModName:_ : Maybe{Qid} -> Attribute [ctor] .
 op module:_ : Maybe{Module} -> Attribute [ctor] .
 op current:_ : Maybe{Qid} -> Attribute [ctor] .
 op top:_ : Maybe{Module} -> Attribute [ctor] .
 op bubbles:_ : TermList -> Attribute [ctor] .
 op file:_ : Maybe{Oid} -> Attribute [ctor] .
 op input:_ : TermList -> Attribute [ctor] .
 op db:_ : Database -> Attribute [ctor] .
 op state:_ : State -> Attribute [ctor] .
 op out:_ : String -> Attribute [ctor] .
 op umi:_ : Oid -> Attribute [ctor] .
 op mi:_ : Oid -> Attribute [ctor] .

 *** Initial value for loading into the parsing metainterpreter
 op modList : -> List{Preload} .
 eq modList = module('TRUTH-VALUE) module('BOOL-OPS) module('TRUTH)
              module('BOOL) module('EXT-BOOL) module('NAT) module('RANDOM)
              module('COUNTER) module('INT) module('RAT) module('FLOAT)
              module('STRING) module('CONVERSION) module('BOUND) 
              module('QID) view('Qid) module('TRIV) view('TRIV)
              module('LIST) module('QID-LIST) 
              module('COMMON-SIGN) module('SPEC-SIGN) module('COMMAND-SIGN) module('PLSS-SIGN) .
              --- module('VALUE) module('MATRIX) 
              --- module('PREDEF-VALUE-FUNCTIONS) 
              --- view('UndefToZero) view('UndefToOne) view('UndefSemi) .
              --- module('PROTEIN) module('THING) module('SOUP) module('MODIFICATION)
              --- module('LOCATION) module('DISH) module('THEOPS) . --- module('CELL) 
              --- module('SOFTSET) .
              --- module('META-LEVEL) module('SS-STRAT) .
              --- module('UNDEF-TO-ZERO) module('UNDEF-TO-ONE) module('UNDEF-TO-SEMI)
 ***(
 eq modList = module('TRUTH-VALUE) module('BOOL-OPS) module('TRUTH) module('BOOL)
              module('EXT-BOOL) module('NAT) module('INT) module('RAT) module('FLOAT)
              module('STRING) module('CONVERSION) module('QID) module('TRIV)
              view('Qid) module('LIST) module('QID-LIST) module('COMMON-SIGN)
              module('SPEC-SIGN) module('COMMAND-SIGN) module('PLSS-SIGN)
              module('VENDING-MACHINE-SIGNATURE).
 eq modList = module('TRUTH-VALUE) module('BOOL-OPS) module('TRUTH) module('BOOL)
              module('EXT-BOOL) module('NAT) module('INT) module('RAT) module('FLOAT)
              module('STRING) module('CONVERSION) module('QID) module('TRIV)
              view('Qid) module('LIST) module('QID-LIST) module('COMMON-SIGN)
              module('SPEC-SIGN) module('COMMAND-SIGN) module('PLSS-SIGN) .
)

 *** Initial value for loading into the user module
 op qModule : -> Qid .
 eq qModule = 'QQ .    --- UNDEF-TO-ZERO  SOFTSET  SS-STRAT   VENDING-MACHINE
 op userModule : -> FModule .
 eq userModule = upModule(qModule, true) .


 *** Run command
 op run : -> Configuration [ctor] .

 ***                                 ***
 ***          PARSE COMMAND          ***
 ***                                 ***

 rl [parseComm] : gotLine(plss, stdin, Text)
    < plss : PLSS | mi: MI, state: idle, AtS >
 => < plss : PLSS | mi: MI, state: parseComm, AtS >
    parseTerm(MI, plss, 'GRAMMAR, none, tokenize(Text), '@Input@) .

 crl [parseComm] :
     parsedTerm(plss, MI, {T, Ty})
     < plss : PLSS | mi: MI, state: parseComm, input: IN, AtS >
  => < plss : PLSS | mi: MI, state: executeComm, input: TL, AtS >
  if TL := extractTerms(T) .

 ***                         ***
 ***          EMPTY          ***
 ***                         ***

 rl [emptyCommList] :
    < plss : PLSS | state: executeComm, input: empty, AtS >
 => < plss : PLSS | state: idle, input: empty, AtS >
    getLine(stdin, plss, "PLSS> ") .

 ***                        ***
 ***          LOAD          ***
 ***                        ***

 crl [loadComm] :
    < plss : PLSS | state: executeComm, input: ('load_['token[T]], INPLST), AtS >
 => < plss : PLSS | state: readFile, input: INPLST, AtS >
    openFile(fileManager, plss, STR, "r")
  if STR := string(downQid(T)) .

 ***                          ***
 ***          REDUCE          ***
 ***                          ***

 crl [redComm] :
     < plss : PLSS | state: executeComm, input: ('red_['bubble[T]], INPLST), module: M, AtS >
  => < plss : PLSS | state: print&executeComm, input: INPLST, module: M, AtS >
     write(stdout, plss, STR)
  if {T', Ty} := metaParse(M, downQidList(T), anyType) /\
     {T'', Ty'} := metaReduce(M, T') /\
     QIL := metaPrettyPrint(M, T'') /\
     STR := "\nResult: " + printTokens(QIL) + "\n" .

 ***                           ***
 ***          SOFTREW          ***
 ***                           ***

 crl [softrewComm] :   --- de momento es igual a redComm (salvo el nombre de la regla y del comando)
     < plss : PLSS | state: executeComm, input: ('softrew_['bubble[T]], INPLST), module: M, AtS >
  => < plss : PLSS | state: print&executeComm, input: INPLST, module: M, AtS >
     write(stdout, plss, STR)
  if {T', Ty} := metaParse(M, downQidList(T), anyType) /\
     {T'', Ty'} := metaReduce(M, T') /\
     QIL := metaPrettyPrint(M, T'') /\
     STR := "\nResult: " + printTokens(QIL) + "\n" .

 ***                            ***
 ***          OPENFILE          ***
 ***                            ***

 rl [openedFile] : openedFile(plss, fileManager, FHIn)
    < plss : PLSS | file: null, state: readFile, AtS >
 => < plss : PLSS | file: FHIn, state: readFile, AtS >
    getLine(FHIn, plss) .

 rl [readingModule] : gotLine(plss, FHIn, Text)
    < plss : PLSS | file: FHIn, out: Read, state: readFile, AtS >
 => if Text == ""
    then < plss : PLSS | file: FHIn, out: Read, state: readFile, AtS >
         closeFile(FHIn, plss)
    else < plss : PLSS | file: FHIn, out: (Read + Text), state: readFile, AtS >
         getLine(FHIn, plss)
    fi .

 ***                               ***
 ***          FILE PARSED          ***
 ***                               ***

 rl [parseModuleMetaparse] :
    < plss : PLSS | out: Read, state: parseModMetaparse, mi: MI, AtS >
 => < plss : PLSS | out: Read, state: parseList, mi: MI, AtS >
    parseTerm(MI, plss, 'GRAMMAR, none, tokenize(Read), '@Input@) .

 ***                               ***
 ***          FILE PARSED          ***
 ***                               ***

 crl [parseModuleNoBubblesOK] :
     parsedTerm(plss, MI, {T, Ty})
     < plss : PLSS | out: Read, state: parseList, mi: MI, input: INPLST, AtS >
  => < plss : PLSS | out: "", state: executeComm, mi: MI, input: (TL, INPLST), AtS >
  if TL := extractTerms(T) .

 ***                                    ***
 ***          FILE PARSE ERROR          ***
 ***                                    ***

 crl [parseModuleNoBubblesError] :
     parsedTerm(plss, MI, noParse(N))
     < plss : PLSS | out: Read, state: parseList, mi: MI, AtS >
  => < plss : PLSS | out: "", state: print&executeComm, mi: MI, AtS >
     write(stdout, plss, printTokens(QIL))
  if QIL := showMsg(tokenize(Read), N) .

 ***                               ***
 ***          MODULE COMM          ***
 ***                               ***

 crl [moduleComm] :
     < plss : PLSS | db: DB, state: executeComm, umi: MI,
                   parsModName: MQ, bubbles: BUBBS, top: MM,
                   input: (Q[TL], INPLST), AtS >
  => < plss : PLSS | db: DB', state: parseModBubbles, umi: MI,
                   parsModName: getName(M), bubbles: TL', top: M,
                   input: INPLST, AtS >
     insertModule(MI, plss, M)
  if (Q ==  'spec!_=_end or Q == 'spec*_=_end) /\
     [M, TL', SI, ERR] := parseModule(Q[TL]) /\
     DB' := DB[getName(M) |-> SI] .

 rl [parseModule_GetFlatModule] :
    insertedModule(plss, MI)
    < plss : PLSS | state: parseModBubbles, umi: MI, parsModName: Q, AtS >
 => < plss : PLSS | state: parseModBubbles, umi: MI, parsModName: Q, AtS >
    showModule(MI, plss, Q, true) .

 crl [parseBubbles] :
     showingModule(plss, MI, M)
     < plss : PLSS | state: parseModBubbles, umi: MI, bubbles: BUBBS,
                   top: TOP, parsModName: Q, current: MQ, db: DB, AtS >
  => < plss : PLSS | state: parseModule, umi: MI, bubbles: empty,
                   top: noMod, parsModName: noQid, current: Q, db: (DB[Q |-> VS]), AtS >
     insertModule(MI, plss, M')
  if [M', VS, QIL] := parseBubbles(TOP, M, BUBBS) .

 rl [parsingComplete] :
    insertedModule(plss, MI)
    < plss : PLSS | state: parseModule, umi: MI, current: Q, AtS >
 => < plss : PLSS | state: getModule, umi: MI, current: Q, AtS >
    showModule(MI, plss, Q, true).

 crl [updateNewModule] :
     showingModule(plss, MI, M)
     < plss : PLSS | state: getModule, umi: MI, current: Q, module: MM, AtS >
  => < plss : PLSS | state: print&executeComm, umi: MI, current: Q, module: M, AtS >
     write(stdout, plss, MSG)
  if MSG := "\nModule " + string(Q) + " introduced.\n\n" .


 *** TODO: parse error

 ***                                    ***
 ***          PRINT & CONTINUE          ***
 ***                                    ***

 rl [print&idle] : wrote(plss, stdout)
    < plss : PLSS | state: print&idle, AtS >
 => < plss : PLSS | state: idle, AtS >
    getLine(stdin, plss, "PLSS> ") .

 rl [print&executeComm] : wrote(plss, stdout)
    < plss : PLSS | state: print&executeComm, AtS >
 => < plss : PLSS | state: executeComm, AtS > .

 ***                               ***
 ***          CLOSE FILE           ***
 ***                               ***

 rl [closedFile] : closedFile(plss, FHIn)
    < plss : PLSS | file: FHIn, state: readFile, AtS >
 => < plss : PLSS | file: null, state: parseModMetaparse, AtS > .

 ***                         ***
 ***          EXIT           ***
 ***                         ***

 rl [exit] :
    < plss : PLSS | state: executeComm, input: ('exit.@Command@), AtS >
 => write(stdout, plss, "Thanks for using PLSS!\n") [print AtS] .

 rl [quit] :
    < plss : PLSS | state: executeComm, input: ('q.@Command@), AtS >
 => write(stdout, plss, "Thanks for using PLSS!\n") .

 ***                        ***
 ***          ERROR         ***
 ***                        ***

 rl [parseCommError] :
    parsedTerm(plss, MI, noParse(N))
    < plss : PLSS | mi: MI, state: parseComm, AtS >
 => < plss : PLSS | mi: MI, state: print&idle, AtS >
    write(stdout, plss, "The introduced command does not exit.\n") .

 ***                          ***
 ***          CREATE          ***
 ***      METAINTERPRETER     ***
 ***                          ***

 rl [init-module] :
    createdInterpreter(plss, interpreterManager, MI)
    < plss : PLSS | state: init, load: module(Q) LP, AtS >
 => < plss : PLSS | state: load-std-db, mi: MI, load: LP, AtS >
    insertModule(MI, plss, upModule(Q, false)) .

 rl [init-view] :
    createdInterpreter(plss, interpreterManager, MI)
    < plss : PLSS | state: init, load: view(Q) LP, AtS >
 => < plss : PLSS | state: load-std-db, mi: MI, load: LP, AtS >
    insertView(MI, plss, upView(Q)) .

 rl [load-predef-module-from-module] :
    insertedModule(plss, MI)
    < plss : PLSS | state: load-std-db, load: module(Q) LP, AtS >
 => < plss : PLSS | state: load-std-db, load: LP, AtS >
    insertModule(MI, plss, upModule(Q, false)) .

 rl [load-predef-view-from-module] :
    insertedModule(plss, MI)
    < plss : PLSS | state: load-std-db, load: view(Q) LP, AtS >
 => < plss : PLSS | state: load-std-db, load: LP, AtS >
    insertView(MI, plss, upView(Q)) .

 rl [load-predef-module-from-view] :
    insertedView(plss, MI)
    < plss : PLSS | state: load-std-db, load: module(Q) LP, AtS >
 => < plss : PLSS | state: load-std-db, load: LP, AtS >
    insertModule(MI, plss, upModule(Q, false)) .

 rl [load-predef-view-from-view] :
    insertedView(plss, MI)
    < plss : PLSS | state: load-std-db, load: view(Q) LP, AtS >
 => < plss : PLSS | state: load-std-db, load: LP, AtS >
    insertView(MI, plss, upView(Q)) .

 rl [load-predef-finished] :
    insertedModule(plss, MI)
    < plss : PLSS | state: load-std-db,  load: nil, AtS > 
 => < plss : PLSS | state: load-grammar, load: nil, AtS >
    insertModule(MI, plss, GRAMMAR) .

 rl [load-grammar-finished] :
    insertedModule(plss, MI)
    < plss : PLSS | state: load-grammar, AtS >
 => < plss : PLSS | state: idle, AtS >
    getLine(stdin, plss, "PLSS> ") .


 ***                        ***
 ***          RUN           ***
 ***                        ***

 eq run =
    <> < plss : PLSS | file: null, out: "", state: init, db: empty,
                     load: modList, current: noQid,
                     parsModName: noQid, bubbles: empty, top: noMod,
                     input: empty, module: userModule >
    createInterpreter(interpreterManager, plss, none) .
endm

set print conceal on .
print conceal module:_ .

set print attribute on .
set show advisories on .

erew run .

*************************************************
eof

red (Tgfb1Dish)
red (PD({CLm | empty}) ([cdc6 = 1]))

red (Tgfb1Dish )


