***************************************
***************************************
%    EJECUCION

cd /Users/santos/Desktop/PLSS12
/Users/santos/Documents/maude-3.1/maude.darwin64 -allow-files plss


red (Tgfb1Dish  [cdc6 = 0])

red (Tgfb1Dish  [cdc6 = 0], [cdkn1a = 0], [cdkn2b = 0], [col1a1 = 0], [col3a1 = 0], [ctgf = *], [fn1 = *], [mmp2 = 0], [pai1 = *], [smad6 = 0], [smad7 = 0], [tgfb1 = 0], [timp1 = 0], [cst6 = 0], [dst = 0], [mmp9 = *], [mylk = 0], [pthlh = *], [gfi1 = 0], [csrp2 = 0], [rorc = *])

red (PD({NUc | empty})  [cdc6 = 0])


softrew (Tgfb1Dish  [cdc6 = 0])

softrew (Tgfb1Dish  ([cdc6 = 0], [cdkn1a = 0], [cdkn2b = 0], [col1a1 = 0], [col3a1 = 0], [ctgf = *], [fn1 = *], [mmp2 = 0], [pai1 = *], [smad6 = 0], [smad7 = 0], [tgfb1 = 0], [timp1 = 0], [cst6 = 0], [dst = 0], [mmp9 = *], [mylk = 0], [pthlh = *], [gfi1 = 0], [csrp2 = 0], [rorc = *]))

softrew (PD({NUc | empty})  [cdc6 = 0])

load softsetfile.txt

load softsetfile1.txt

load softsetfile2.txt

loadstrat undefSemi

softrew (Tgfb1Dish ([cdc6 = 0]))

loadstrat undefZero

softrew (Tgfb1Dish ([cdc6 = 0]))


***************************************
eof


-------------------------------

softdishselect MySoftdish >> dish PD({NUc | empty}) . attributes ([cdc6 = 0], [cdkn1a = 0]) .

softdishselect MySoftdish >> (kkk) (kkk)

specsoftrew

