fmod CHEMICALOPS is inc THEOPS .

sort Lipid GlycoLipid .
subsort  GlycoLipid < Lipid < Chemical .
sort SPeptide .                            *** synthetic peptide
subsort SPeptide < Chemical .

sort TLR2ligand .    subsort TLR2ligand < Chemical .
sort TLR3ligand .    subsort TLR3ligand < Chemical .
sort TLR4ligand .    subsort TLR4ligand < Chemical .
sort TLR5ligand .    subsort TLR5ligand < Chemical .
sort TLR7ligand .    subsort TLR7ligand < Chemical .
sort TLR8ligand .    subsort TLR8ligand < Chemical .
sort TLR9ligand .    subsort TLR9ligand < Chemical .
sort TLR12ligand .   subsort TLR12ligand < Chemical .
sort TLR26ligand .   subsort TLR26ligand < Chemical .
sort TLR78ligand .    subsort TLR78ligand < Chemical .

op 1Butanol : -> Chemical [ctor] .
op 2DOG : -> Chemical [ctor] .
op 3M002 : -> Chemical [ctor] .
op 3M003 : -> Chemical [ctor] .
op 3Methyladenine : -> Chemical [ctor] .
op 5Aza2Deoxycytidine : -> Chemical [ctor] .
op 5Fluorouracil  : -> Chemical .
op 5Iodotubercidin : -> Chemical [ctor] .
op 5ThioGlucose : -> Chemical [ctor] .
op 5Z7Oxozeaenol : -> Chemical [ctor] .
op 8CPTcAMP : -> Chemical [ctor] .
op 8SPT : -> Chemical [ctor] .
op 15dPGJ2 : -> Chemical [ctor] .
op 125dihydroxyvitaminD3 : -> Chemical [ctor] .

op 13HODE : -> Chemical [ctor metadata "(\
  (PubChemCID 6443013)\
  (synonyms \"13-hydroxy-9,11-octadecadienoic acid\"))"] .

op 15HETE : -> Chemical [ctor metadata "(\
  (PubChemCID 5353283)\
  (synonyms \"15-hydroxy-5,8,11,13-eicosatetraenoic acid\"))"] .

op A23187 : -> Chemical [ctor] .
op ABT737 : -> Chemical [ctor] .
op Ac-LDL : -> Chemical [ctor] .
op Ac-WEHD-AMC : -> Chemical [ctor] .
op Ac-YVAD-AOM : -> Chemical [ctor] .
op Ac-YVAD-CHO : -> Chemical [ctor] .
op Ac-YVAD-CMK : -> Chemical [ctor] .

op Acetate : -> Chemical [ctor metadata "(\
  (KeggCpdID C00033)\
  (category Hidden)\
  (synonyms \"Acetic acid\"\
            \"Ethanoic acid\"))"] .

op Acridine-Orange : -> Chemical [ctor] .
op ActinomycinD : -> Chemical [ctor] .
op Adenosine : -> Chemical [ctor] .
op ADP : -> Chemical [ctor] .

op Adriamycin : -> Chemical  [ctor metadata "(\
  (KeggCpdID C01661)\
  (PubChemCID 31703)\
  (synonyms \"Doxorubicin\"))"] .

op AEG40730 : -> Chemical [ctor] .
op Aerolysin : -> Chemical [ctor] .
op AG490 : -> Chemical [ctor] .
op AG825 : -> Chemical [ctor] .
op AG1295 : -> Chemical [ctor] .
op AG1296 : -> Chemical [ctor] .
op AG1478 : -> Chemical [ctor] .
op AgNO3 : -> Chemical [ctor] .
op Aicar : -> Chemical [ctor] .
op AktI12 : -> Chemical [ctor] .
op AktInhibitor : -> Chemical [ctor] .
op ALLM : -> Chemical [ctor] .
op ALLN : -> Chemical [ctor] .
op AMDA : -> Chemical [ctor] .
op Amiloride : -> Chemical [ctor] .
op AminoAcidEsters : -> Chemical [ctor] .
op AminoAcids : -> Chemical [ctor] .
op AMP : -> Chemical [ctor] .
op Amrinone : -> Chemical [ctor] .
op AnacardicAcid : -> Chemical [ctor] .

op Anisomycin : -> Chemical [ctor metadata "(\
  (KeggCpdID C11281)\
  (PubChemCID 253602))"] .

op AntimycinA : -> Chemical [ctor] .
op AOPCP : -> Chemical [ctor] .
op Aphidicolin : -> Chemical [ctor] .
op APMA : -> Chemical [ctor] .

op ArachidonicAcid : -> Chemical [ctor metadata "(\
  (PubChemCID 444899)\
  (synonyms \"cis-5,8,11,14-Eicosatetraenoic acid\"))"] .

op Arsenite : -> Chemical [ctor] .
op As2O3  : -> Chemical .
op AsCl3 : -> Chemical [ctor] .
op Aspirin : -> Chemical [ctor] .
op ATP : -> Chemical [ctor] .
op ATRA : -> Chemical [ctor] .
op AZD0530 : -> Chemical [ctor] .
op Bacitracin : -> Chemical [ctor] .
op Bafilomycin : -> Chemical [ctor] .
op BaptaAM : -> Chemical [ctor] .
op Batimastat : -> Chemical [ctor] .
op Bay117082 : -> Chemical [ctor] .
op BAY439006 : -> Chemical [ctor] .
op BCAMP : -> Chemical [ctor] .
op BCH : -> Chemical [ctor] .
op BD-FMK : -> Chemical [ctor] .
op beta-mercaptoethanol : -> Chemical [ctor] .
op BID1870 : -> Chemical [ctor] .
op BIM1 : -> Chemical [ctor] .
op BIRB796 : -> Chemical [ctor] .
op Bisindolylmaleimide-I : -> Chemical [ctor] .
op Bisindolylmaleimide-V : -> Chemical [ctor] .
op BismuthAmmoniumCitrate : -> Chemical [ctor] .

op Bleomycin : -> Chemical  [ctor metadata "(\
  (KeggCpdID Bleomycin)\
  (PubChemCID 5360373))"] .

op BLP : -> Chemical [ctor] .
op BMS345541 : -> Chemical [ctor] .
op Bombesin : -> Chemical [ctor] .
op Bortezomib  : -> Chemical .
op BRDU : -> Chemical [ctor] .
op Brefeldin-A : -> Chemical [ctor] .
op BSO : -> Chemical [ctor] .
op Bucladesine : -> Chemical [ctor] .
op BV6 : -> Chemical [ctor] .
op BzATP : -> Chemical [ctor] .
op c-diAMP : -> Chemical [ctor] .
op c-diGMP : -> Chemical [ctor] .
op C6Cer : -> Chemical [ctor] .
op Caffeine  : -> Chemical .
op CaffeicAcid  : -> Chemical .
op Calcitrol : -> Chemical [ctor] .
op Calcium : -> Chemical [ctor] .
op Calmidazolium : -> Chemical [ctor] .
op Calphostin : -> Chemical [ctor] .
op CalyculinA : -> Chemical [ctor] .
op cAMP : -> Chemical [ctor] .
op Camptothecin : -> Chemical [ctor] .
op Cantharidin : -> Chemical [ctor] .
op capped-mRNA : -> Chemical [ctor] .
op Carbachol : -> Chemical [ctor] .
op Carbamazepine : -> Chemical [ctor] .
op CCCP : -> Chemical [ctor] .
op CdCl2 : -> Chemical [ctor] .
op CEP1347 : -> Chemical [ctor] .
op CEP11004 : -> Chemical [ctor] .

op Ceramide : -> Lipid [ctor metadata "(\
  (KeggCpdID C00195)\
  (category Carrier)\
  (synonyms \"N-Acylsphingosine\"))"] .

op CGP57380 : -> Chemical [ctor] .
op CGP77675 : -> Chemical [ctor] .
op CGS21680 : -> Chemical [ctor] .
op Chelerythrine : -> Chemical [ctor] .
op Chloropromazine : -> Chemical [ctor] .
op Chloroquine : -> Chemical [ctor] .
op Chlorpromazine : -> Chemical .
op CHX : -> Chemical [ctor] .
op CI1040 : -> Chemical [ctor] .
op Cisplatin : -> Chemical [ctor] .
op CKI7 : -> Chemical [ctor] .
op Cl-Radicicol-A : -> Chemical [ctor] .
op CMP : -> Chemical [ctor metadata "(\
  (KeggCpdID C00055)\
  (KeggGlycID G10621)\
  (category Hidden)\
  (synonyms \"Cytidine 5'-monophosphate\"\
            \"Cytidylic acid\"))"] .

op CMP-Neu5Ac : -> Chemical [ctor metadata "(\
  (KeggCpdID C00128)\
  (KeggGlycID G10616)\
  (category Hidden)\
  (synonyms \"CMP-N-acetylneuraminate\"\
            \"CMP-N-acetylneuraminic acid\"))"] .

op CNI1493 : -> Chemical [ctor] .
op CoA : -> Chemical [ctor metadata "(\
  (KeggCpdID C00010)\
  (category Hidden)\
  (synonyms \"Coenzyme A\"\
            \"CoA-SH\"))"] .

op CoCl2 : -> Chemical [ctor] .
op Colchicine : -> Chemical [ctor] .
op Compound-1 : -> Chemical [ctor] .
op Compound-56 : -> Chemical [ctor] .
op Compound-506 : -> Chemical [ctor] .
op Compound-C : -> Chemical [ctor] .
op Comptothecin : -> Chemical [ctor] .
op ConA : -> Chemical [ctor] .
op ConcanamycinA : -> Chemical [ctor] .
op CoumermycinA : -> Chemical [ctor] .
op CP118556 : -> Chemical [ctor] .
op CpG : -> TLR9ligand [ctor] .
op CpG-1471  : -> TLR9ligand .
op CpG-1668 : -> TLR9ligand [ctor] .
op CpG-1826 : -> TLR9ligand [ctor] .
op CpG-2006 : -> TLR9ligand [ctor] .
op CpG-2084 : -> TLR9ligand [ctor] .
op CpG-2088 : -> TLR9ligand [ctor] .
op CpG-2216 : -> TLR9ligand [ctor] .
op CpG-A151  : -> TLR9ligand .
op CpG-AAC : -> TLR9ligand [ctor] .
op CpG-D19 : -> TLR9ligand [ctor] .
op CpG-D35 : -> TLR9ligand [ctor] .
op CpG-H154  : -> TLR9ligand .
op CpG-K3  : -> TLR9ligand .
op CpG-K23 : -> TLR9ligand [ctor] .
op CpGa : -> TLR9ligand [ctor] .
op CpGb : -> TLR9ligand [ctor] .
op Crebtide : -> SPeptide [ctor metadata "(\
  (stype Peptide)\
  (sequence EILSRRPSYRK)\
  (comment \"peptide substrate for Msks\"))"] .

op Crosstide : -> SPeptide [ctor metadata "(\
  (stype Peptide)\
  (sequence GRPRTSSFAEG)\
  (comment \"peptide substrate for Akts Sgks\"))"] .

op CsA : -> Chemical [ctor] .
op CT1746 : -> Chemical [ctor] .
op CTX : -> Chemical .
op Ctxb : -> Chemical [ctor] .
op Curcumin : -> Chemical [ctor] .
op CuSO4 : -> Chemical [ctor] .
op Cyclodextrin : -> Chemical [ctor] .
op Cytarabine : -> Chemical [ctor] .
op CytochalasinD : -> Chemical [ctor] .
op D4476 : -> Chemical [ctor] .
op DADLE : -> Chemical [ctor] .
op DAG : -> Lipid  [ctor metadata "(\
  (KeggCpdID C00165)\
  (category Hidden)\
  (synonyms \"Diacylglycerol\"\
            \"Diglyceride\"))"] .

op DAMGO : -> Chemical [ctor] .
op Dantrolene : -> Chemical [ctor] .
op Dasatinib : -> Chemical [ctor] .
op DCFH-DA : -> Chemical [ctor] .
op DeltorphinI : -> Chemical [ctor] .
op DEVD-FMK : -> Chemical [ctor] .
op Dexamethasone : -> Chemical [ctor] .
op DextranSulfate : -> Chemical [ctor] .
op DFX  : -> Chemical .
op DHE : -> Chemical [ctor] .
op DHS : -> Chemical [ctor] .
op Diamide : -> Chemical [ctor] .
op Diazoxide : -> Chemical [ctor] .
op dibutyryl-cAMP : -> Chemical [ctor] .
op Dicoumarol : -> Chemical [ctor] .
op Dipyridamole : -> Chemical [ctor] .
op DMAT : -> Chemical [ctor] .
op DMNQ  : -> Chemical .
op DMOG  : -> Chemical .
op DNCB : -> Chemical [ctor] .

op Dolichol : -> Lipid [ctor metadata "(\
  (KeggCpdID C00381)\
  (category Hidden)\
  (synonyms \"Dolichol\"))"] .

op DOLP : -> Lipid [ctor metadata "(\
  (KeggCpdID C00110)\
  (KeggGlycID G10622)\
  (category Carrier)\
  (synonyms \"Dolichyl phosphate\"\
            \"Dolichol phosphate\"))"] .

op DOLP-Glc : -> GlycoLipid [ctor metadata "(\
  (KeggCpdID C01246)\
  (KeggGlycID G10618)\
  (category Hidden)\
  (synonyms \"Dolichyl D-glucosyl phosphate\"))"] .

op DOLP-Man : -> GlycoLipid [ctor metadata "(\
  (KeggCpdID C03862)\
  (KeggGlycID G10617)\
  (category Hidden)\
  (synonyms \"Dolichyl phosphate D-mannose\"\
            \"Dolichyl D-mannosyl phosphate\"))"] .

op DOLPP : -> Lipid [ctor metadata "(\
  (KeggCpdID C00621)\
  (category Carrier)\
  (synonyms \"Dolichyl diphosphate\"\
            \"Dolichol diphosphate\"))"] .

op DOPE : -> Chemical [ctor] .
op Dotap : -> Chemical [ctor] .
op DPDPE : -> Chemical [ctor] .
op DPhenylalanine : -> Chemical [ctor] .
op DPI : -> Chemical [ctor] .
op DPPE : -> Chemical [ctor] .
op DRB : -> Chemical [ctor] .
op dsDNA : -> Chemical [ctor] .
op dsRNA : -> Chemical [ctor] .
op DTT : -> Chemical [ctor] .
op Dynasore : -> Chemical [ctor] .
op E64 : -> Chemical [ctor] .
op EAA : -> Chemical [ctor] .
op EB1089 : -> Chemical [ctor] .
op Ebselen : -> Chemical [ctor] .
op EDTA : -> Chemical [ctor] .
op EGTA : -> Chemical [ctor] .
op EHNA : -> Chemical [ctor] .
op EKI : -> Chemical [ctor] .
op Epinephrine : -> Chemical [ctor] .
op Epoxomicin  : -> Chemical .
op ErkInhibitorI : -> Chemical [ctor] .
op Erlotinib : -> Chemical [ctor] .
op Estradiol : -> Chemical [ctor] .
op EtBr : -> Chemical [ctor] .

op Etoposide : -> Chemical  [ctor metadata "(\
  (KeggCpdID C01576)\
  (PubChemCID 36462)\
  (synonyms \"VP-16\"))"] .


op FAM-YVAD-FMK : -> Chemical [ctor] .
op FCCP : -> Chemical [ctor] .
op Fenofibrate : -> Chemical [ctor] .
op FeTPPS : -> Chemical [ctor] .
op Fetuin : -> Chemical [ctor] .
op Filipin : -> Chemical [ctor] .
op FK506 : -> Chemical [ctor] .
op Flagellin : -> TLR5ligand [ctor] .
op Fludara : -> Chemical [ctor] .
op FMK : -> Chemical [ctor] .
op Forskolin : -> Chemical [ctor] .
op FRNK : -> Chemical [ctor] .
op FSL1 : -> TLR26ligand [ctor] .
op FTI277 : -> Chemical [ctor] .
op Fucoidan : -> Chemical [ctor] .
op Fugene : -> Chemical [ctor] .
op FYVE-domain : -> Chemical [ctor] .
op Galactose : -> Chemical [ctor metadata "(\
  (KeggCpdID C00124)\
  (category Hidden)\
  (synonyms \"D-Galactose\"))"] .

op GalNAc : -> Chemical [ctor metadata "(\
  (KeggCpdID C01132)\
  (category Hidden)\
  (synonyms \"N-Acetyl-D-galactosamine\"))"] .

op GDC08679 : -> Chemical [ctor] .

op GDP : -> Chemical [ctor metadata "(\
  (KeggCpdID C00035)\
  (KeggGlycID G10620)\
  (category Hidden)\
  (synonyms \"Guanosine 5'-diphosphate\"\
            \"Guanosine diphosphate\"))"] .

op GDP-LFuc : -> Chemical [ctor metadata "(\
  (KeggCpdID C00325)\
  (KeggGlycID G10615)\
  (category Hidden)\
  (synonyms \"GDP-L-fucose\"))"] .

op GDP-Man : -> Chemical [ctor metadata "(\
  (KeggCpdID C00096)\
  (KeggGlycID G10614)\
  (category Hidden)\
  (synonyms \"GDP-D-mannose\"\
            \"GDP-alpha-D-mannose\"\
            \"GDP-mannose\"))"] .

op Gefitinib : -> Chemical [ctor] .
op Geldanamycin : -> Chemical [ctor] .
op Gemfibrozil : -> Chemical [ctor] .
op Genistein : -> Chemical [ctor] .
op GGTI2147 : -> Chemical [ctor] .
op GI254023X : -> Chemical [ctor] .

op Glucose : -> Chemical [ctor metadata "(\
  (KeggCpdID C00031 D00009)\
  (category Hidden)\
  (synonyms \"D-Glucose\"\
            \"Dextrose\"))"] .

op Glutamine : -> Chemical [ctor] .
op GM1 : -> Chemical [ctor] .
op GM3 : -> Chemical [ctor] .
op GMP : -> Chemical [ctor] .
op Go6976 : -> Chemical [ctor] .
op Go6983 : -> Chemical [ctor] .
op GPNA : -> Chemical [ctor] .
op GSH : -> Chemical [ctor] .
op GSK3inhibitorI : -> Chemical [ctor] .
op GSK3inhibitorII : -> Chemical [ctor] .
op GSK3inhibitorIX : -> Chemical [ctor] .
op GSK3inhibitorXI : -> Chemical [ctor] .
op GSNO : -> Chemical [ctor] .
op GTP : -> Chemical [ctor] .
op GW742 : -> Chemical [ctor] .
op GW3965 : -> Chemical [ctor] .
op GW5074 : -> Chemical [ctor] .
op GW7845 : -> Chemical [ctor] .
op GW9662 : -> Chemical [ctor] .
op GW501516 : -> Chemical [ctor] .
op H2O : -> Chemical [ctor metadata "(\
  (KeggCpdID C00001)\
  (category Hidden)\
  (synonyms \"Water\"))"] .

op H2O2 : -> Chemical [ctor] .
op H7 : -> Chemical [ctor] .
op H8 : -> Chemical [ctor] .
op H89 : -> Chemical [ctor] .
op Heparin : -> Chemical [ctor] .
op HerbimycinA : -> Chemical [ctor] .
op Herceptin : -> Chemical [ctor] .
op HgCl2 : -> Chemical [ctor] .
op Histidinol : -> Chemical [ctor] .
op HKLM : -> TLR2ligand [ctor] .
op HMMSK : -> SPeptide [ctor] .
op HMROK : -> SPeptide [ctor] .
op HMRSK : -> SPeptide [ctor] .
op HMS6K : -> SPeptide [ctor] .
op HMSGK : -> SPeptide [ctor] .
op Hyaluronan : -> Chemical [ctor] .

op Hydroxyurea : -> Chemical [ctor metadata "(\
  (KeggCpdID C07044)\
  (PubChemCID 3657)\
  (synonyms \"Hydroxycarbamide\"))"] .

op Hypericin : -> Chemical [ctor] .
op IBMX : -> Chemical [ctor] .
op IBOP : -> Chemical [ctor] .
op IC261 : -> Chemical [ctor] .
op IEAL : -> Chemical [ctor] .
op IETD-FMK : -> Chemical [ctor] .
op IKK2InhibitorIV : -> Chemical [ctor] .
op Imatinib : -> Chemical [ctor] .
op Imiquimod : -> TLR7ligand [ctor] .
op Indomethacin : -> Chemical [ctor] .

op InoAcylP : -> Chemical [ctor metadata "(\
  (KeggID none)\
  (category Carrier)\
  (synonyms \"Ino(acyl)-P\"))"] .

op InoP : -> Chemical [ctor metadata "(\
  (KeggID none)\
  (category Carrier)\
  (synonyms \"Ino-P\"))"] .

op Inositol : ->  Chemical [ctor metadata "(\
  (KeggCpdID C00137)\
  (category Carrier)\
  (synonyms \"myo-Inositol\"))"] .

op IodoaceticAcid : -> Chemical [ctor] .
op Ionomycin : -> Chemical [ctor] .
op isoButanol : -> Chemical [ctor] .
op Isoproterenol : -> Chemical [ctor] .
op Jak-Inhibitor-I : -> Chemical [ctor] .
op Jak3-Inhibitor-I : -> Chemical [ctor] .
op Jasplakinolide : -> Chemical [ctor] .
op JNK-Inhibitor-I : -> Chemical [ctor] .
op JNK-Inhibitor-II : -> Chemical [ctor] .
op JSH23 : -> Chemical [ctor] .
op K2Cr2O7 : -> Chemical [ctor] .
op K252a : -> Chemical [ctor] .
op Kaede : -> Chemical [ctor] .
op Kaempferol : -> Chemical [ctor] .
op Kainate : -> Chemical [ctor] .
op KCl : -> Chemical [ctor] .
op Kenpaullone : -> Chemical [ctor] .
op KIC : -> Chemical [ctor] .
op KN62 : -> Chemical [ctor] .
op KN93 : -> Chemical [ctor] .
op KPSD1 : -> Chemical [ctor] .
op KT5270 : -> Chemical [ctor] .
op KT5720 : -> Chemical [ctor] .
op KU55933 : -> Chemical [ctor] .
op L690330 : -> Chemical [ctor] .
op Lactacystin : -> Chemical [ctor] .
op Lactose : -> Chemical [ctor metadata "(\
  (KeggID G10504 C00243 D00046)\
  (category Hidden)\
  (synonyms \"Galb1-4Glc\"))"] .

op LambdaPPase : -> Chemical .
op Lapatinib : -> Chemical [ctor] .
op LatrunculinA : -> Chemical [ctor] .
op LatrunculinB : -> Chemical [ctor] .
op Leucine : -> Chemical [ctor] .
op Leupeptin : -> Chemical [ctor] .
op LFMA13 : -> Chemical [ctor] .
op LG101305 : -> Chemical [ctor] .
op LiCl : -> Chemical [ctor] .

op LinoleicAcid : -> Chemical [ctor metadata "(\
  (PubChemCID 5280450)\
  (synonyms \"cis-9,cis-12-Octadecadienoic acid\"))"] .

op Lipid-A : -> Lipid [ctor] .
op Lipid-A-406 : -> Lipid [ctor] .
op Lipid-A-505 : -> Lipid [ctor] .
op Lipid-A-pLA : -> Lipid [ctor] .
op Lipofectamine : -> Chemical [ctor] .
op Lithium : -> Chemical [ctor] .
op LKBtide : -> SPeptide [ctor metadata "(\
  (stype Peptide)\
  (sequence LSNLYHQGKFLQTFCGSPLYRRR)\
  (comment \"peptide substrate for Lkb1\"))"] .

op LLL : -> Chemical [ctor] .
op LLNV : -> Chemical [ctor] .
op LMB : -> Chemical [ctor] .
op Loxoribine : -> Chemical [ctor] .
op LPA : -> Chemical [ctor] .

op Lps : -> TLR4ligand  [ctor metadata "(\
  (KeggCpdID C00338)\
  (PubChemCID 11970143)\
  (synonyms \"Lipopolysaccharide\"))"] .

op Lps-Ft : -> Chemical [ctor] .
op Lps-Ft-LVS : -> Chemical [ctor] .
op Lps-P.gingivalis : -> Chemical [ctor] .
op LTA : -> Chemical [ctor] .
op LTA-Sa : -> Chemical [ctor] .
op LY294002 : -> Chemical [ctor] .
op MAA : -> Chemical [ctor] .
op Maitotoxin : -> Chemical [ctor] .
op Malp2 : -> Chemical [ctor] .
op Mannan : -> Chemical [ctor] .
op Mannitol : -> Chemical [ctor] .

op Mannose : -> Chemical [ctor metadata "(\
  (KeggCpdID C00159)\
  (category Hidden)\
  (synonyms \"D-Mannose\"\
            \"Seminose\"\
            \"Carubinose\"))"] .

op Marimastat : -> Chemical [ctor] .
op Menadione : -> Chemical [ctor] .
op Metformin : -> Chemical [ctor] .
op Methyl-beta-cyclodextrin : -> Chemical [ctor] .
op Methylamine : -> Chemical [ctor] .
op Methylglyoxal : -> Chemical [ctor] .
op Methylpyruvate : -> Chemical [ctor] .
op Mevalonolactone : -> Chemical [ctor] .
op MG132 : -> Chemical [ctor] .
op MG273 : -> Chemical [ctor] .
op MgCl2 : -> Chemical [ctor] .
op MitoQ : -> Chemical [ctor] .
op ML7 : -> Chemical [ctor] .
op MLC : -> Chemical [ctor] .
op MMS : -> Chemical [ctor] .
op MNNG : -> Chemical [ctor] .
op Monensin : -> Chemical [ctor] .
op Monodansylcadaverine : -> Chemical [ctor] .
op mRNA : -> Chemical [ctor] .
op MSU : -> Chemical [ctor] .
op myr-PKI-peptide : -> SPeptide [ctor] .
op myr-SIYRRGARRWRKL : -> Chemical [ctor] .
op Myxothiazol : -> Chemical [ctor] .
op N-acetyl-L-cysteine : -> Chemical [ctor] .
op N6-Methyl-2-deoxyadenosine : -> Chemical [ctor] .
op NaCl : -> Chemical [ctor] .
op NADPH : -> Chemical [ctor] .
op NaF : -> Chemical [ctor] .
op Naltrindole : -> Chemical [ctor] .
op NaN3 : -> Chemical [ctor] .
op NBDpeptide : -> SPeptide [ctor] .
op NBTI : -> Chemical [ctor] .
op NCI3 : -> Chemical [ctor] .

op NCS : -> Chemical [ctor metadata "(\
  (KeggCpdID C12049)\
  (PubChemCID 447545)\
  (synonyms \"Neocarzinostatin-Chromophore\"))"] .

op NDGA : -> Chemical [ctor] .
op NEAA : -> Chemical [ctor] .
op NEM : -> Chemical [ctor] .
op NiCl2 : -> Chemical [ctor] .
op Nifedipine : -> Chemical [ctor] .
op Nigericin : -> Chemical [ctor] .
op Nitrobensylthioinosine : -> Chemical [ctor] .
op NLVS  : -> Chemical .
op NMMA  : -> Chemical .
op Nocodazole : -> Chemical [ctor] .
op NOG : -> Chemical [ctor] .
op Novobiocin : -> Chemical [ctor] .
op NS2028 : -> Chemical [ctor] .
op NU7026 : -> Chemical [ctor] .
op Nutlin3a  : -> Chemical .
op Nystatin : -> Chemical [ctor] .
op O2 : -> Chemical [ctor] .
op Okadaic-acid : -> Chemical [ctor] .
op Oligomycin : -> Chemical [ctor] .
op Orthovanadate : -> Chemical [ctor] .
op OspC : -> Chemical [ctor] .
op Ouabain : -> Chemical [ctor] .
op OVA : -> Chemical [ctor] .
op P35 : -> Chemical [ctor] .
op PA : -> Chemical [ctor] .
op Palmitoyl-CoA : -> Lipid [ctor metadata "(\
  (KeggCpdID C00033)\
  (category Hidden)\
  (synonyms \"Hexadecanoyl-CoA\"))"] .

op Pam3Csk4 : -> TLR12ligand [ctor] .
op PAO : -> Chemical [ctor] .
op PAP : ->  Chemical [ctor metadata "(\
  (KeggCpdID C00054)\
  (category Hidden)\
  (synonyms \"Adenosine 3',5'-bisphosphate\"\
            \"3'-Phosphoadenylate\"\
            \"Phosphoadenosine phosphate\"))"] .

op PAPS : -> Chemical [ctor metadata "(\
  (KeggCpdID C00053)\
  (category Hidden)\
  (synonyms \"3'-Phosphoadenylyl sulfate\"\
            \"3'-Phosphoadenosine 5'-phosphosulfate\"\
            \"3'-Phospho-5'-adenylyl sulfate\"))"] .

op Parthenolide : -> Chemical [ctor] .
op PC : -> Chemical [ctor] .
op PD98059 : -> Chemical [ctor] .
op PD144795 : -> Chemical [ctor] .
op PD146176 : -> Chemical [ctor] .
op PD153035 : -> Chemical [ctor] .
op PD153095 : -> Chemical [ctor] .
op PD158780 : -> Chemical [ctor] .
op PD168393 : -> Chemical [ctor] .
op PD169316 : -> Chemical [ctor] .
op PD180970 : -> Chemical [ctor] .
op PD184352 : -> Chemical [ctor] .
op PD325901 : -> Chemical [ctor] .
op PDA : -> Chemical [ctor] .
op PDB : -> Chemical [ctor] .
op PDI : -> Chemical [ctor] .
op PE : -> Lipid [ctor metadata "(\
  (KeggCpdID C00350)\
  (category Hidden)\
  (synonyms \"Phosphatidylethanolamine\"\
            \"Cephalin\"))"] .

op Pepstatin A : -> Chemical [ctor] .
op Peroxynitrite : -> Chemical [ctor] .
op Pervanadate : -> Chemical [ctor] .
op PGE2 : -> Chemical [ctor] .
op Pgn : -> Chemical [ctor] .
op PGN-LTA : -> Chemical [ctor] .
op PHA : -> Chemical [ctor] .
op PHA665752 : -> Chemical [ctor] .
op PHA818637 : -> Chemical [ctor] .
op Phenformin : -> Chemical [ctor] .
op Phleomycin : -> Chemical [ctor] .
op pHMMSK : -> SPeptide [ctor] .
op pHMROK : -> SPeptide [ctor] .
op pHMRSK : -> SPeptide [ctor] .
op pHMS6K : -> SPeptide [ctor] .
op pHMSGK : -> SPeptide [ctor] .
op PI3P : -> Lipid [ctor] .
op PI4P : -> Lipid [ctor] .
op PI5P : -> Lipid [ctor] .
op PI34P2 : -> Lipid [ctor] .
op PI35P2 : -> Lipid [ctor] .
op PI45P2 : -> Lipid [ctor metadata "(\
  (KeggCpdID C04637)\
  (synonyms \"PIP2\"))"] .

op PI103 : -> Chemical [ctor] .
op PIB  : -> Chemical .
op Piceatannol : -> Chemical [ctor] .
op PIFtide : -> Chemical [ctor] .
op PIP3 : -> Lipid [ctor] .
op PKCzPS : -> Chemical [ctor] .
op PKI : -> Chemical [ctor] .
op PLX4720 : -> Chemical [ctor] .

op PMA : -> Chemical [ctor metadata "(\
  (KeggCpdID C05151)\
  (PubChemCID 27924)\
  (synonyms \"Phorbol 12-myristate 13-acetate\"\
            \"12-O-Tetradecanoylphorbol 13-acetate\"\
            \"TPA\"))"] .

op pNPP : -> Chemical [ctor] .
op Poly-dAdT : -> Chemical [ctor] .
op Poly-dAdT-dTdA : -> Chemical [ctor] .
op Poly-dIdC : -> Chemical [ctor] .
op PolyA : -> Chemical [ctor] .
op PolyAC : -> Chemical [ctor] .
op PolyAU : -> Chemical [ctor] .
op PolyC : -> Chemical [ctor] .
op PolyG : -> Chemical [ctor] .
op PolyGluTyr : -> Chemical [ctor] .
op PolyI : -> Chemical [ctor] .
op PolyIC : -> TLR3ligand [ctor] .
op PolymyxinB : -> Chemical [ctor] .
op PolyU : -> Chemical [ctor] .
op PotasiumDichromate : -> Chemical [ctor] .
op PP1 : -> Chemical [ctor] .
op PP2 : -> Chemical [ctor] .
op PP3 : -> Chemical [ctor] .
op PP242 : -> Chemical [ctor] .
op Probenecid : -> Chemical [ctor] .
op PS : -> Lipid [ctor] .
op PS1145 : -> Chemical [ctor] .
op PSI : -> Chemical [ctor] .
op PTD-p65 : -> Chemical [ctor] .
op PtdIns : -> Lipid [ctor metadata "(\
  (KeggCpdID C01194)\
  (category Carrier)\
  (synonyms \"Phosphatidylinositol\"))"] .

op PTX : -> Chemical [ctor] .
op Pyrithione : -> Chemical [ctor] .
op PyrrolidineDithiocarbamate : -> Chemical [ctor] .
op PyrrolidineDithiocarbonate : -> Chemical [ctor] .
op Pyruvate : -> Chemical [ctor] .
op R837 : -> Chemical [ctor] .
op R847 : -> Chemical [ctor] .
op R848 : -> TLR78ligand [ctor] .
op Rapamycin : -> Chemical [ctor] .
op Resveratrol : -> Chemical [ctor] .
op RetinoicAcid : -> Chemical [ctor] .
op Ribavirin : -> Chemical [ctor] .
op RNA40-Dotap : -> Chemical [ctor] .
op RNA41-Dotap : -> Chemical [ctor] .
op RNA42-Dotap : -> Chemical [ctor] .
op RNA92s : -> Chemical [ctor] .
op Ro318220 : -> Chemical [ctor] .
op Roscovitine : -> Chemical [ctor] .
op Rosiglitazone : -> Chemical [ctor] .
op Rotenone : -> Chemical [ctor] .
op Rottlerin : -> Chemical [ctor] .
op RSLA : -> Chemical [ctor] .
op S1p : -> Chemical [ctor] .
op S3I201 : -> Chemical [ctor] .
op S6peptide : -> SPeptide [ctor metadata "(\
  (stype Peptide)\
  (sequence RRLSSLRA)\
  (comment \"peptide substrate for S6ks\"))"] .

op SalicylihalamideA : -> Chemical [ctor] .
op Sant7 : -> Chemical [ctor] .
op SB202190 : -> Chemical [ctor] .
op SB202474 : -> Chemical [ctor] .
op SB203580 : -> Chemical [ctor] .
op SB216763 : -> Chemical [ctor] .
op SB415286 : -> Chemical [ctor] .
op SB431542 : -> Chemical [ctor] .
op SB505124 : -> Chemical [ctor] .
op SC514 : -> Chemical [ctor] .
op Serum : -> Chemical [ctor] .
op SH5 : -> Chemical [ctor] .
op Simvastatin : -> Chemical [ctor] .
op SKF86002 : -> Chemical [ctor] .
op SmacMimetic : -> Chemical [ctor] .
op SN50 : -> SPeptide [ctor] .
op SN50M : -> SPeptide [ctor] .
op SNA1 : -> Chemical [ctor] .
op SNAP : -> Chemical [ctor] .
op SNCEE : -> Chemical [ctor] .
op SNP : -> Chemical [ctor] .
op SodiumButyrate : -> Chemical [ctor] .
op Sorafenib : -> Chemical [ctor] .
op Sorbitol : -> Chemical [ctor] .
op Sp-cAMPS : -> Chemical [ctor] .
op SP26 : -> Chemical [ctor] .
op SP600125 : -> Chemical [ctor] .
op Sphingosine : -> Lipid [ctor] .
op SPI : -> SPeptide [ctor] .
op SPNO  : -> Chemical .
op SQ22536 : -> Chemical [ctor] .
op ssDNA : -> Chemical [ctor] .
op ssRNA : -> Chemical [ctor] .
op ssRNA40 : -> TLR8ligand [ctor] .
op Staurosporine : -> Chemical [ctor] .
op STI571 : -> Chemical [ctor] .
op STO609 : -> Chemical [ctor] .
op SU5402  : -> Chemical .
op SU5416 : -> Chemical [ctor] .
op SU6656 : -> Chemical [ctor] .
op Sucrose : -> Chemical [ctor] .
op Sulfasalazine : -> Chemical [ctor] .
op Suramin : -> Chemical [ctor] .
op T1317 : -> Chemical [ctor] .
op T0901317 : -> Chemical [ctor] .
op TAPI1 : -> Chemical [ctor] .
op TAPI2 : -> Chemical [ctor] .
op Tautomycin : -> Chemical [ctor] .
op Taxol : -> Chemical [ctor] .
op TBB : -> Chemical [ctor] .
op TBHP : -> Chemical [ctor] .
op TBHQ : -> Chemical [ctor] .
op tButanol : -> Chemical [ctor] .
op TCEP : -> Chemical [ctor] .
op TCR-specific-Ag : -> Chemical [ctor] .
op TFP : -> Chemical [ctor] .
op Thapsigargin : -> Chemical [ctor] .
op Theophylline : -> Chemical [ctor] .
op Tilorone : -> Chemical [ctor] .
op Tilorone-874 : -> Chemical [ctor] .
op Tirap-Peptide-Inhibitor : -> SPeptide [ctor] .
op TLCK : -> Chemical [ctor] .
op TLR3L : -> TLR3ligand [ctor metadata "(\
  (category Family)\
  (members PolyIC))"] .

op TLR7L : -> TLR7ligand [ctor metadata "(\
  (category Family)\
  (members Imiquimod))"] .

op TLR9L : -> TLR9ligand [ctor metadata "(\
  (category Family)\
  (members CpG CpGa CpGb CpG-1471 CpG-1668 CpG-1826 CpG-2006 CpG-2084\
           CpG-2088 CpG-2216 CpG-A151 CpG-AAC CpG-D19 CpG-D35 CpG-H154\
           CpG-K3 CpG-K23))"] .

op TM6008  : -> Chemical .
op TMO : -> Chemical [ctor] .
op Topotecan : -> Chemical [ctor] .
op Torin1 : -> Chemical [ctor] .
op ToxinB : -> Chemical [ctor] .
op TPCK : -> Chemical [ctor] .
op TPEN : -> Chemical [ctor] .
op TrichostatinA : -> Chemical [ctor] .
op tRNA : -> Chemical [ctor] .
op Troglitazone : -> Chemical [ctor] .
op TSH : -> Chemical [ctor] .
op Tunicamycin  : -> Chemical .
op Tyrphostin1 : -> Chemical [ctor] .
op U0126 : -> Chemical [ctor] .
op U46619 : -> Chemical [ctor] .
op U50488 : -> Chemical [ctor] .
op U73122 : -> Chemical [ctor] .
op U73343 : -> Chemical [ctor] .
op UDP : -> Chemical [ctor metadata "(\
  (KeggCpdID C00015)\
  (KeggGlycID G10619)\
  (category Hidden)\
  (synonyms \"Uridine 5'-diphosphate\"))"] .

op UDP-Gal : -> Chemical [ctor metadata "(\
  (KeggCpdID C00052)\
  (KeggGlycID G10609)\
  (category Hidden)\
  (synonyms \"UDP-D-galactose\"\
            \"UDP-galactose\"\
            \"Uridene diphosphate galactose\"\
            \"UDP-alpha-D-galactose\"))"] .

op UDP-GalNAc : -> Chemical [ctor metadata "(\
  (KeggCpdID C00203)\
  (KeggGlycID G10611)\
  (category Hidden)\
  (synonyms \"UDP-N-acetyl-D-galactosamine\"))"] .

op UDP-Glc : -> Chemical [ctor metadata "(\
  (KeggCpdID C00029)\
  (KeggGlycID G10608)\
  (category Hidden)\
  (synonyms \"UDP-D-glucose\"\
            \"UDP-glucose\"))"] .

op UDP-GlcA : -> Chemical [ctor metadata "(\
  (KeggCpdID C00167)\
  (KeggGlycID G10612)\
  (category Hidden)\
  (synonyms \"UDP-D-glucuronate\"\
            \"UDP-D-glucuronic acid\"\
            \"UDP-glucuronate\"\
            \"UDP-glucuronic acid\"))"] .

op UDP-GlcNAc : -> Chemical [ctor metadata "(\
  (KeggCpdID C00043)\
  (KeggGlycID G10614)\
  (category Hidden)\
  (synonyms \"UDP-N-acetyl-D-glucosamine\"\
            \"UDP-N-acetylglucosamine\"))"] .

op UDP-Xyl : -> Chemical [ctor metadata "(\
  (KeggCpdID C00190)\
  (KeggGlycID G10613)\
  (category Hidden)\
  (synonyms \"UDP-D-xylose\"\
            \"UDP-xylose\"))"] .

op UMP : -> Chemical [ctor metadata "(\
  (KeggCpdID C00105)\
  (category Hidden)\
  (synonyms \"Uridylic acid\"\
            \"Uridine monophosphate\"\
            \"Uridine 5'-monophosphate\"\
            \"5'Uridylic acid\"))"] .

op UTP : -> Chemical [ctor] .
op Valinomycin : -> Chemical [ctor] .
op ValproicAcid : -> Chemical [ctor] .
op Vanadate : -> Chemical [ctor] .
op VegfR2Inhibitor1 : -> Chemical [ctor] .
op Verapamil : -> Chemical [ctor] .
op Vinblastine : -> Chemical [ctor] .
op VPC32179 : -> Chemical [ctor] .
op Wedelolactone  : -> Chemical .
op WGA : -> Chemical [ctor] .
op Wortmannin : -> Chemical [ctor] .
op WY14643 : -> Chemical [ctor] .
op Xanthine : -> Chemical [ctor] .
op Y27632 : -> Chemical [ctor] .
op Z-DEVD-FMK : -> Chemical [ctor] .
op Z-FA-FMK : -> Chemical [ctor] .
op Z-IETD-FMK : -> Chemical [ctor] .
op Z-LLF-CHO : -> Chemical [ctor] .
op Z-VAD-FMK : -> Chemical [ctor] .
op Z-YVAD-FMK : -> Chemical [ctor] .
op ZnCl2 : -> Chemical [ctor] .
op ZnOAc2 : -> Chemical [ctor] .
op ZnSO4 : -> Chemical [ctor] .
op ZnXx : -> Chemical [ctor] .
op ZSTK474 : -> Chemical [ctor] .
op ZVAD : -> Chemical [ctor] .
op Zymosan : -> Chemical [ctor] .



endfm

