fmod MODIFICATIONOPS is
     inc MODIFICATION .

op acetyl : -> Modification .          *** acetylated
op acetyl : Site -> Modification .     *** acetylated on a specific site
op act : -> Modification .             *** activated
op cleaved : -> Modification .         *** cleaved by a protease
op conj : -> Modification .            *** used for mono or poly ubiquitin bound to any protein (FK2 antibody)
op degraded : -> Modification .        *** used in rules to show the little man on the stairs
op dimer : -> Modification .           *** dimerized
op GDP : -> Modification .             *** bound to GDP
op GDPbS : -> Modification [ctor] .    *** bound to GDPbS
op glyc : -> Modification .          *** glycosylated
op glyc : Gcode -> Modification .    *** glycosylated with Gcode
op GMPPCP : -> Modification [ctor] .   *** bound to GMPPCP
op GMPPNP : -> Modification [ctor] .   *** bound to GMPPNP
op gpi : -> Modification .          *** attached to protein via gpi linkage
op gpi : Gcode -> Modification .    *** Gcode attached to protein via gpi linkage that includes carrier lipid
op GTP : -> Modification .             *** bound to GTP
op GTPgS  : -> Modification [ctor] .   *** bound to GTPgS
op K48poly : -> Modification .         *** polymerized via K48 linkages
op K48ubiq : -> Modification .         *** covalently bound to ubiquitin polymerized via K48 linkages
op K63poly : -> Modification .         *** polymerized via K63 linkages
op K63ubiq : -> Modification .         *** covalently bound to ubiquitin polymerized via K48 linkages
op methyl : -> Modification .          *** methylated
op methyl : Site -> Modification .     *** methylated on a specific site
op mono : -> Modification .            *** not polymerized
op nedd : -> Modification .            *** neddylated
op NucFree : -> Modification [ctor] .  *** not bound to any nucleotide
op off : -> Modification .             *** gene transcription is off
op on : -> Modification .              *** gene transcription is on
op p25 : -> Modification .             *** Cdk5r1 processing
op p34 : -> Modification .             *** TgfbR1 cleavage product
op p50 : -> Modification .             *** Nfkb1 processing
op p52 : -> Modification .             *** Nfkb2 processing
op p100 : -> Modification .            *** Nfkb2 processing
op p105 : -> Modification .            *** Nfkb1 processing
op phos :       -> Modification .      *** phosphorylated
op phos : Site  -> Modification .      *** phosphorylated on a specific site
op poly : -> Modification .            *** polymerized
op poly1 : -> Modification .           *** used for free Ubiq-poly chains
op poly2 : -> Modification .           *** used for free Ubiq-poly chains
op poly3 : -> Modification .           *** used for free Ubiq-poly chains
op sumo : -> Modification .            *** sumoylated
op thiophos : -> Modification [ctor] . *** phosed with thiophosphate
op ubiq : -> Modification .            *** covalently conjugated to ubiquitin
op ubiq : Site -> Modification .       *** covalently conjugated with ubiquitin at a specific site
op unphos : -> Modification .          *** used for datums only to highlight change in phos
op Yphos : -> Modification .           *** phosphorylated on Tyrosine

endfm
