fmod SIGNATUREOPS is inc THEOPS .

op ACTIN-TREADMILL-ON : -> Signature .
op ANGIOGENESIS : -> Signature .
op APOPTOSIS : -> Signature .
op CTNNB1-DEGRADED : -> Signature .
op PROLIFERATION : -> Signature .
op PROTEIN-SYNTHESIS-ON : -> Signature .
op QUIESCENT : -> Signature [ctor] .
op STRESS-FIBERS : -> Signature .
op NFKB-REPORTER-ON : -> Signature .
op NFKB-RESPONSE-ELEMENT-BOUND : -> Signature .

endfm
