fmod STRESSOPS is inc THEOPS .

op AA-deprivation : -> Stress [ctor] .
op Anoxia : -> Stress [ctor] .
op anti-Itgav-adherence : -> Stress [ctor] .
op anti-Itgb1-adherence : -> Stress [ctor] .
op Au197Ions : -> Stress [ctor] .
op BSA-adherence : -> Stress [ctor] .
op BSS : -> Stress [ctor] .
op BSS-Glucose : -> Stress [ctor] .
op c-diAMP-transfection : -> Stress [ctor] .
op c-diGMP-transfection : -> Stress [ctor] .
op C12Ions : -> Stress [ctor] .
op Col4-adherence : -> Stress [ctor] .
op Collagen-adherence : -> Stress [ctor] .
op CpG-D19-transfection : -> Stress [ctor] .
op CpGa-transfection : -> Stress [ctor] .
op CpGb-transfection : -> Stress [ctor] .
op Csf3-deprivation : -> Stress [ctor] .
op CT-DNA-transfection : -> Stress [ctor] .
op culture : -> Stress [ctor] .
op DSB : -> Stress [ctor] .  *** DNA strand break
op DSB-Induction : -> Stress [ctor] .  *** site-specific DSB-Induction by I-PpoI transfection
op EBBS : -> Stress [ctor] .
op EBSS : -> Stress [ctor] .
op EMCV-infection : -> Stress [ctor] .      *** EncephaloMyoCarditis virus
op FasL-XL : -> Stress [ctor] .
op Fixed-S-aureus-cells : -> Stress [ctor] .
op Fn1-adherence : -> Stress [ctor] .
op Ft-LVS-infection : -> Stress [ctor] .
op Ft-U112-infection : -> Stress [ctor] .
op G0-release : -> Stress [ctor] .
op Glucose-deprivation : -> Stress [ctor] .
op Growth-medium : -> Stress [ctor] .
op Heat-Shock : -> Stress [ctor] .
op HS5-coculture : -> Stress [ctor] .
op HSV-infection : -> Stress [ctor] .      *** Herpesviridae family
op HSV1-DNA-transfection : -> Stress [ctor] .
op HSV1-infection : -> Stress [ctor] .      *** Herpes Simplex Virus type 1
op Hypoxia : -> Stress [ctor] .
op Ifna-deprivation : -> Stress [ctor] .
op IL2-deprivation : -> Stress [ctor] .
op IL3-deprivation : -> Stress [ctor] .
op IL4-deprivation : -> Stress [ctor] .
op IL12-deprivation : -> Stress [ctor] .
op IR : -> Stress [ctor] .                *** Ionizing-Radiation
op Itgav-adherence : -> Stress [ctor] .
op Itgb1-adherence : -> Stress [ctor] .
op L.monocytogenes-infection : -> Stress [ctor] .
op Laminin-adherence : -> Stress [ctor] .
op Leucine-deprivation : -> Stress [ctor] .
op LowpH : -> Stress [ctor] .
op MicroLaser : -> Stress [ctor] .   *** Laser microirradiation + BrdU treatment
op NDV-infection : -> Stress [ctor] .  *** Newcastle Disease Virus
op Ni64Ions : -> Stress [ctor] .
op PLL-adherence : -> Stress [ctor] .
op Poly-dAdT-dTdA-transfection : -> Stress [ctor] .
op Poly-dAdT-transfection : -> Stress [ctor] .
op Poly-dIdC-transfection : -> Stress [ctor] .
op PolyIC-transfection : -> Stress [ctor] .
op PolyU-transfection : -> Stress [ctor] .
op Reseeding : -> Stress [ctor] .  *** usually release from G0 density arrest
op RNA40-transfection : -> Stress [ctor] .
op RNA42-transfection : -> Stress [ctor] .
op RSV-infection : -> Stress [ctor] .  *** respiratory syncytial virus
op Serum-depletion : -> Stress [ctor] .
op Serum-deprivation : -> Stress [ctor] .
op SeV-infection : -> Stress [ctor] .  *** Sendai virus
op Sphingomyelinase : -> Stress [ctor] .  *** to increase intracellular Sphingosine and/or Ceramide
op Suspension : -> Stress [ctor] .
op U238Ions : -> Stress [ctor] .
op UV : -> Stress [ctor] .
op VACV-DNA-transfection : -> Stress [ctor] .
op VACV-infection : -> Stress [ctor] .  *** Vaccinia virus
op VSV-infection : -> Stress [ctor] .  *** Vesicular Stomatitis Virus
op VSV-RNP-transfection : -> Stress [ctor] .
op XenonIons : -> Stress [ctor] .



op GTPgS-aToxin : -> Stress [ctor] .
*** addition of GTPgS to cells after permeabilization with alpha-toxin

endfm
